### ISSUE TITLE
Unable to throw 409 Conflict Https status

### ISSUE THREAD

**Issue by harshalb007** [spring-cloud-samples/bookstore-service-broker#23]
Hello team,
I am implementing the service broker using Spring.

I have provided an implementation class for ServiceInstanceBindingService.
In this, according to the OSBAPI specification given [here](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#api-overview)
If someone provides already existing bindingId but with different attributes, we should throw 409 status.
But I am unable to find a way to achieve this.
Will you please help me out.

Thanks.

**Comment by royclarkson** [comment]
Hi, I answered this over on the Spring Cloud Open Service Broker project. Thanks.

https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/285#issuecomment-627945714
